import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Diccionario",
  description: "Generated by create next app",
    icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className="font-sans bg-white text-gray-900 dark:bg-slate-900 dark:text-slate-100 transition-colors duration-150">
        <ThemeProvider
          attribute="class"
          defaultTheme="system" // O "light" o "dark" si prefieres un default específico
          enableSystem
          disableTransitionOnChange // Recomendado por next-themes para App Router
        >
          <Header />
          <main className="min-h-screen p-4 sm:p-6 max-w-3xl mx-auto">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
