import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-white text-black dark:bg-gray-900 dark:text-white">
        <main className="min-h-screen p-6 max-w-3xl mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
